export const ADD_SESSIONID  = 'ADD_SESSIONID';
export const SERVICE_SUCCESS  = 'SERVICE_SUCCESS';
export const SERVICE_FAIL  = 'SERVICE_FAIL';
export const ADD_EMAIL_ID  = 'ADD_EMAIL_ID';
export const ADD_MEMBERSHIP  = 'ADD_MEMBERSHIP';
export const ADD_MOBILENUMBER  = 'ADD_MOBILENUMBER';
export const ADD_PROFILE="ADD_PROFILE";
export const ADD_SLUG="ADD_SLUG";
export const REPLY_FLAG  = 'REPLY_FLAG';

export const MEMBER_AWARD  = 'MEMBER_AWARD';
export const MEMBER_BIO  = 'MEMBER_BIO';
export const MEMBER_EDUCATION  = 'MEMBER_EDUCATION';
export const MEMBER_EMPLOYMENT = "MEMBER_EMPLOYMENT";
export const MEMBER_SHIP = "MEMBER_SHIP";
export const NETWORK_PROFILE  = 'NETWORK_PROFILE';
export const FEED_ID  = 'FEED_ID';

export const PROFILE_PIC = 'PROFILE_PIC';
export const PROFILE_BANNER='PROFILE_BANNER';
export const VIDEO_PREVIEW_URL='VIDEO_PREVIEW_URL';
export const AUDIO_PREVIEW_URL='AUDIO_PREVIEW_URL';
export const FETCH_PHOTOS_DATA='FETCH_PHOTOS_DATA';

export const APP_TIMELINE_THEME = 'APP_TIMELINE_THEME';

export const ORIENTATION='ORIENTATION';
export const CHANGEPROFILEPIC='CHANGEPROFILEPIC';


export const USER_ROLES='USER_ROLES';
